# Generated by Django 2.0.1 on 2018-10-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0003_auto_20181021_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='state',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Ocupado', 'Ocupado'), ('Ausente', 'Ausente'), ('No disponible', 'No disponible')], default='Disponible', max_length=20),
            preserve_default=False,
        ),
    ]
