# Generated by Django 2.0.1 on 2018-11-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0004_profesor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesor',
            name='image',
            field=models.ImageField(default='', upload_to='profesores/'),
            preserve_default=False,
        ),
    ]
