# Generated by Django 2.0.2 on 2018-09-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180925_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='horaInicio',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='fechaAsesoria',
            field=models.CharField(choices=[('Lu', 'Lunes'), ('Ma', 'Martes'), ('Mi', 'Miercoles'), ('Ju', 'Jueves'), ('Vi', 'Viernes')], max_length=12),
        ),
    ]
