# Generated by Django 2.0.2 on 2018-09-25 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180925_0147'),
    ]

    operations = [
        migrations.AddField(
            model_name='asesoria',
            name='codProfesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Profesor'),
            preserve_default=False,
        ),
    ]
