# Generated by Django 2.0.1 on 2018-09-26 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_asesoria_codprofesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='asesoria',
            name='fechaAsesoria',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=12),
        ),
        migrations.AddField(
            model_name='favorito',
            name='asesoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Asesoria'),
        ),
        migrations.AddField(
            model_name='favorito',
            name='nombreAlumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Alumno'),
        ),
    ]
