# Generated by Django 2.0.1 on 2018-09-26 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180926_0350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cita',
            old_name='nombreAlumno',
            new_name='alumno',
        ),
        migrations.RenameField(
            model_name='favorito',
            old_name='nombreAlumno',
            new_name='alumno',
        ),
    ]
