# Generated by Django 2.0.1 on 2018-09-26 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180926_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asesoria',
            name='fechaAsesoria',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=12),
        ),
    ]
