# Generated by Django 2.0.1 on 2018-10-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profesor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('codigoUlima', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=300)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Asesoria')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Alumno')),
                ('asesoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Asesoria')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='favorito',
            unique_together={('asesoria', 'alumno')},
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('asesoria', 'alumno')},
        ),
    ]
