# Generated by Django 2.0.1 on 2018-11-06 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0003_auto_20181021_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
                ('comment', models.CharField(max_length=200)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumno.Cita')),
            ],
        ),
    ]
