# Generated by Django 2.0.1 on 2018-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0004_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='semana',
            field=models.IntegerField(default=13),
            preserve_default=False,
        ),
    ]
