# Generated by Django 2.0.1 on 2018-11-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumno', '0005_cita_semana'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='finalizado',
            field=models.BooleanField(default=False),
        ),
    ]
