# Generated by Django 2.0.1 on 2018-10-21 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsesoria', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=12)),
                ('horaInicio', models.TimeField(default='12:00')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(max_length=50)),
                ('seccion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrepProfesor', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=20)),
                ('codigoUlima', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='codProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='codCurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Curso'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='codProfesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Profesor'),
        ),
        migrations.AddField(
            model_name='asesoria',
            name='lugar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profesor.Salon'),
        ),
    ]
