# Generated by Django 2.0.1 on 2018-10-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesor', '0002_profesor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
